### ISSUE TITLE
WQ: "The Troubled Fortification" can't be completed the normal way.

### ISSUE THREAD

**Issue by Kolaib777** [Dixdros/DDON_Bugs#3]
This quest can be taken from Etna in Dana inn.
it was working before BBM update, but now its stuck at:
![The troubled fortification](https://github.com/user-attachments/assets/ec2e86bc-c75a-4ade-a517-6ede73bb8ddb)
the objective is to go to Farana ruins and talk to a Npc (Alan) there to start a fight aginst a lvl70 Wight and 3 lvl70 strix, before the BBM update the area where the Npc Alan is at was empty, and the Wight and the strix had a Key icon above their head, upon killing them a nearby door opens that leads to a room with a chest (not required to complete the dungeon).
Now the same area has 3 new mobs Dark skeleton, a Rat and a Skeleton mage, they also have a key icon above their heads and after killing them the same door opens.
i killed the new mobs, the door to the room opens, then i talked to the npc to start the fight with the quest enemies, upon killing them the quest is stuck as shown in the screenshot above, however teleporting to a safe zone (WDT or Dana inn) and then returning to the quest site (Farana ruins), the quest enemies respawned (without talking to the npc again and the Dark skeleton the rat and the skeleton mage are not there) the door to the room opens and the quest is updated properly and can be turned in in Danna inn.
 (i did try not killing the new mobs and going straight to the npc to start the fight with all of them at once, killed all enemies same issue).

**Comment by pacampbell** [comment]
@Dixdros Since we have a quest which corresponds to this gate now, we should remove the normal enemies from this group or place quest monsters in different positions in the same group so they can spawn.

**Comment by Kolaib777** [comment]
Correction to (i did try not killing the new mobs and going straight to the npc to start the fight with all of them at once, killed all enemies same issue).
actually running straight to the Npc and triggering the fight with the quest enemies Despawn the lvl70 Rat; Dark Skeleton and the Skeleton Mage.

**Comment by Dixdros** [comment]
> @Dixdros Since we have a quest which corresponds to this gate now, we should remove the normal enemies from this group or place quest monsters in different positions in the same group so they can spawn.

i will do that !

**Comment by Dixdros** [comment]
![image](https://github.com/user-attachments/assets/bfcbbcca-896e-4593-9753-fea491b1d789)
Quest is Fixed

**Comment by Dixdros** [comment]
![image](https://github.com/user-attachments/assets/7ae555a4-31d6-44cb-9ceb-6f4bacc4eb25)
