### ISSUE TITLE
"The Troubled Fortification" quest doesn't progress + invisible enemy

### ISSUE THREAD

**Issue by ramzaat** [Dixdros/DDON_Bugs#5]
Playing solo through the quest "The Troubled Fortification," talked to Alan to spawn the enemies (two Strix and one Wight) and one of the two Strix was invisible. After clearing the enemies, the quest updates to 'Check the search target's well-being' but no interactions can be made with him as he's still in combat mode it seems, and reloading the area and returning does not make him interactable.

![image](https://github.com/user-attachments/assets/e081b962-c99c-4d3b-bd1e-b11e52a8c617)

**Comment by Dixdros** [comment]
this Issue should be "fixed" let me know if its worked

**Comment by Kolaib777** [comment]
> this Issue should be "fixed" let me know if its worked

Still not working, the difference now is the Wight spawn with one invisible Strix, upon teleporting to a safe zone (Dana or WDT) and returning to the quest site, u find The whight with 2 Strix (visible) without talking to the Npc (Alan), killing them will update the quest properly and it can be turned in in Dana Inn.
the new mobs (Rat, Dark Skeleton and Skeleton Mage, pretty sure they were not there before BBM update) are still there.

**Comment by Dixdros** [comment]
![Uploading image.png…]()

**Comment by Dixdros** [comment]
![image](https://github.com/user-attachments/assets/6f2a2117-7768-47a4-84cf-115d5cfb7141)
